FROM busybox:latest AS kaniko-executor
RUN echo kaniko-executor

FROM busybox:latest AS kaniko-debug
RUN echo kaniko-debug

FROM busybox:latest AS kaniko-slim
RUN echo kaniko-slim

FROM busybox:latest AS kaniko-warmer
RUN echo kaniko-warmer

